# Generated by Django 5.1.7 on 2025-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=255)),
                ('case_urgency', models.IntegerField()),
                ('evidence_count', models.IntegerField(default=0)),
                ('case_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
