# Generated by Django 5.1.6 on 2025-04-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_regularuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularUser',
        ),
    ]
